Repository razorpay/razorpay-woocommerce, pull requests merged in 2024-02, with the labels that each got.

#526 TerraWallet
  includes/api/cart.php
  woo-razorpay.php
Labels: enhancement, checkout, TestingNotRequired

#533 Revert Instant refund
  woo-razorpay.php
Labels: TestingNotRequired

#532 Version Bump 4.6.0
  readme.txt
  woo-razorpay.php
Labels: release, TestingNotRequired

#535 RTB fixes
  woo-razorpay.php
Labels: TestingNotRequired

#534 Support for checkout blocks
  checkout-block.php
  checkout_block.js
  woo-razorpay.php
Labels: TestingNotRequired

#536 Instant refund fix
  woo-razorpay.php
Labels: TestingNotRequired

#537 Version bump 4.6.1
  readme.txt
  woo-razorpay.php
Labels: TestingNotRequired

#538 Shipping Engine Support for woocommerce
  woo-razorpay.php
Labels: TestingNotRequired
